# Generated by Django 4.2.8 on 2023-12-21 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0013_delete_promotionsmodel'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionsmodel',
            name='carwash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='carwash.carwashmodel', verbose_name='Автомойка'),
        ),
    ]
