# Generated by Django 4.2.8 on 2023-12-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('carwash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='carwash.carwashmodel', verbose_name='Мойка')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
                'ordering': ('carwash',),
            },
        ),
    ]
