# Generated by Django 4.2.8 on 2023-12-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0005_carwashimagemodel_carwashservicesmodel_and_more'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='ContactsModel',
        ),
    ]
