# Generated by Django 4.2.8 on 2023-12-20 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0010_alter_carwashratingmodel_carwash_and_more'),
        ('contacts', '0002_rename_contacts_contactsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='carwash',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='carwash.carwashmodel', verbose_name='Мойка'),
        ),
    ]
