# Generated by Django 4.2.8 on 2023-12-21 11:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contactsmodel_id_alter_contactsmodel_carwash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsmodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
