# Generated by Django 4.2.8 on 2023-12-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contactsmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsmodel',
            name='website',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Сайт'),
        ),
    ]
