# Generated by Django 4.2.8 on 2023-12-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contactsmodel_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
