# Generated by Django 4.2.8 on 2023-12-27 19:38

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contactsmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsmodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
    ]
