# Generated by Django 4.2.8 on 2023-12-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('car', 'Легковой автомобиль'), ('suv', 'Внедорожник'), ('crossover', 'Кроссовер'), ('overs', 'другое')], max_length=9, verbose_name='Тип автомобиля'),
        ),
    ]
