# Generated by Django 4.2.8 on 2023-12-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0003_alter_carwashmodel_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashtypemodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Тип автомойки'),
        ),
    ]
