# Generated by Django 4.2.8 on 2023-12-18 20:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('carwash', '0004_alter_carwashtypemodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='Фото автомойки')),
                ('avatar', models.BooleanField(default=False, verbose_name='На аватарку')),
            ],
            options={
                'verbose_name': 'Фотография автомойки',
                'verbose_name_plural': 'Фотографии автомойки',
            },
        ),
        migrations.CreateModel(
            name='CarWashServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='MetroStationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('latitude', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Неверное указание широты, должно быть вида 55.752378', regex='^-?([0-8]?[0-9]|90)(\\.[0-9]{1,10})$')], verbose_name='Широта')),
                ('longitude', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Неверное указание долготы, должно быть вида 55.752378', regex='^-?([0-9]{1,2}|1[0-7][0-9]|180)(\\.[0-9]{1,10})$')], verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Станция метро',
                'verbose_name_plural': 'Станции метро',
            },
        ),
        migrations.CreateModel(
            name='NearestMetroStationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name='Расстояние до автомойки')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Акция автомойки',
                'verbose_name_plural': 'Акции автомойки',
            },
        ),
        migrations.RemoveField(
            model_name='carwashmodel',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='carwashmodel',
            name='price_list',
        ),
        migrations.AddField(
            model_name='carwashmodel',
            name='latitude',
            field=models.CharField(default='55.7520233', max_length=13, validators=[django.core.validators.RegexValidator(message='Неверное указание широты, должно быть вида 55.752378', regex='^-?([0-8]?[0-9]|90)(\\.[0-9]{1,10})$')], verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='carwashmodel',
            name='longitude',
            field=models.CharField(default='37.6174994', max_length=14, validators=[django.core.validators.RegexValidator(message='Неверное указание долготы, должно быть вида 55.752378', regex='^-?([0-9]{1,2}|1[0-7][0-9]|180)(\\.[0-9]{1,10})$')], verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='carwashmodel',
            name='over_information',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='carwashmodel',
            name='legal_person',
            field=models.BooleanField(default=False, verbose_name='Работа с юридическими лицами'),
        ),
        migrations.AlterField(
            model_name='carwashmodel',
            name='loyalty',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Лояльность'),
        ),
        migrations.AlterField(
            model_name='carwashmodel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='carwashmodel',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carwash.carwashtypemodel', verbose_name='Тип автомойки'),
        ),
        migrations.AlterField(
            model_name='carwashtypemodel',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Тип автомойки'),
        ),
        migrations.AddConstraint(
            model_name='carwashmodel',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='unique_car_wash_coordinates'),
        ),
        migrations.AddField(
            model_name='promotionsmodel',
            name='carwash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carwashmodel', verbose_name='Автомойка'),
        ),
        migrations.AddField(
            model_name='nearestmetrostationmodel',
            name='carwash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carwashmodel', verbose_name='Автомойка'),
        ),
        migrations.AddField(
            model_name='nearestmetrostationmodel',
            name='metro_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.metrostationmodel', verbose_name='Станция метро'),
        ),
        migrations.AddConstraint(
            model_name='metrostationmodel',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='unique_metro_coordinates'),
        ),
        migrations.AddField(
            model_name='carwashservicesmodel',
            name='carwash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carwashmodel', verbose_name='Автомойка'),
        ),
        migrations.AddField(
            model_name='carwashservicesmodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicesmodel', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='carwashimagemodel',
            name='carwash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carwashmodel', verbose_name='Автомойка'),
        ),
        migrations.AddField(
            model_name='carwashmodel',
            name='metro',
            field=models.ManyToManyField(through='carwash.NearestMetroStationModel', to='carwash.metrostationmodel', verbose_name='Ближайшие станции метро.'),
        ),
        migrations.AddField(
            model_name='carwashmodel',
            name='service',
            field=models.ManyToManyField(through='carwash.CarWashServicesModel', to='services.servicesmodel', verbose_name='Оказываемые услуги'),
        ),
    ]
