# Generated by Django 4.2.8 on 2023-12-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0005_carwashimagemodel_carwashservicesmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carwashservicesmodel',
            options={'verbose_name': 'Цена услуги', 'verbose_name_plural': 'Цены услуг'},
        ),
        migrations.AlterModelOptions(
            name='nearestmetrostationmodel',
            options={'verbose_name': 'Ближайшая станция метро', 'verbose_name_plural': 'Ближайшие станции метро'},
        ),
    ]
