# Generated by Django 4.2.8 on 2023-12-19 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carwash', '0007_carwashratingmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carwashratingmodel',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Оценка автомойки', 'verbose_name_plural': 'Оценки автомоек'},
        ),
        migrations.AlterField(
            model_name='carwashratingmodel',
            name='carwash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='carwash.carwashmodel'),
        ),
        migrations.AlterField(
            model_name='carwashratingmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
