# Generated by Django 4.2.8 on 2023-12-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0008_alter_carwashratingmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearestmetrostationmodel',
            name='distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Расстояние до автомойки'),
        ),
        migrations.AddConstraint(
            model_name='nearestmetrostationmodel',
            constraint=models.UniqueConstraint(fields=('carwash', 'metro_station'), name='unique_carwash_metro'),
        ),
    ]
