# Generated by Django 4.2.8 on 2023-12-20 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carwash', '0009_alter_nearestmetrostationmodel_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashratingmodel',
            name='carwash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carwashmodel'),
        ),
        migrations.AlterField(
            model_name='carwashratingmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
