# Generated by Django 4.2.8 on 2023-12-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0012_alter_carwashmodel_latitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromotionsModel',
        ),
    ]
