# Generated by Django 4.2.8 on 2023-12-22 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0014_carwashmodel_payment_carwashmodel_rest_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashmodel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default='55.752023', max_digits=8, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='carwashmodel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default='37.617499', max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота'),
        ),
    ]
