# Generated by Django 4.2.8 on 2023-12-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0015_alter_carwashmodel_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashimagemodel',
            name='image',
            field=models.URLField(verbose_name='Ссылка на фото автомойки'),
        ),
    ]
