# Generated by Django 4.2.8 on 2023-12-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0017_remove_carwashmodel_metro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashmodel',
            name='type',
            field=models.ManyToManyField(to='carwash.carwashtypemodel', verbose_name='Тип автомойки'),
        ),
    ]
