# Generated by Django 4.2.8 on 2023-12-27 19:46

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0018_alter_carwashmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashmodel',
            name='payment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Картой'), ('online', 'Онлайн'), ('SBP', 'СБП')], help_text='Выберите способ оплаты', max_length=40, null=True, verbose_name='Способ оплаты'),
        ),
    ]
