# Generated by Django 4.2.8 on 2024-01-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0019_alter_carwashmodel_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashimagemodel',
            name='image',
            field=models.ImageField(upload_to='carwash/', verbose_name='Фото автомойки'),
        ),
    ]
