# Generated by Django 4.2.8 on 2023-12-21 16:54

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicesmodel_rest_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='payment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Картой'), ('online', 'Онлайн'), ('SBP', 'СБП')], default='cash', help_text='Выберите способ оплаты', max_length=30, null=True, verbose_name='Способ оплаты'),
        ),
    ]
