# Generated by Django 4.2.8 on 2023-12-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicesmodel_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmodel',
            name='name',
            field=models.CharField(db_index=True, help_text='Название услуги', max_length=200, unique=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='servicesmodel',
            name='rest_room',
            field=models.BooleanField(default=False, help_text='Наличие комнаты отдыха', verbose_name='Комната отдыха'),
        ),
    ]
