# Generated by Django 4.2.8 on 2023-12-21 17:02

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicesmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmodel',
            name='payment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Картой'), ('online', 'Онлайн'), ('SBP', 'СБП')], help_text='Выберите способ оплаты', max_length=30, null=True, verbose_name='Способ оплаты'),
        ),
    ]
