# Generated by Django 4.2.8 on 2023-12-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicesmodel_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesmodel',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='servicesmodel',
            name='rest_room',
        ),
    ]
