# Generated by Django 4.2.8 on 2023-12-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_servicesmodel_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
    ]
