# Generated by Django 4.2.8 on 2023-12-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_servicesmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Ключевое слово', max_length=100, unique=True, verbose_name='Ключевое слово')),
            ],
            options={
                'verbose_name': 'Ключевое слово услуги',
                'verbose_name_plural': 'Ключевые слова услуг',
                'ordering': ('name',),
            },
        ),
    ]
