# Generated by Django 4.2.8 on 2023-12-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedulemodel_delete_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemodel',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], null=True, verbose_name='День недели'),
        ),
    ]
