# Generated by Django 4.2.8 on 2023-12-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedulemodel_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemodel',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], null=True, verbose_name='День недели'),
        ),
    ]
