version: '3.8'

services:

  frontend:
    image: carwash2023/car-wash-frontend:latest
    volumes:
      - ./data/frontend/:/app/result_build/
    env_file:
      - ./.env

  postgres:
    image: postgres:14.4-alpine
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../static-back/:/var/html/static-back/
      - ../../media/:/var/html/media/
      - ./data/frontend/build:/usr/share/nginx/html/

volumes:
  data:
