version: '3.3'


services:

# Backend-project
  backend:
    image: carwash2023/car-wash-backend:latest
    restart: always
    expose:
      - "8000"
    command: >
      sh -c "chmod +x /app/infra/docker-entrypoint.sh && /app/infra/docker-entrypoint.sh"
    volumes:
      - ./data/static/:/app/static/
      - ./data/media/:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db


# Postgres DB
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/postgres_data/:/var/lib/postgresql/data
    env_file:
      - ./.env


  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/static/:/var/html/static/
      - ./data/media/:/var/html/media/
